resources:
  - name: authorized_keys_repo
    icon: github
    type: git
    source:
      uri: https://github.com/acuteaura/authorized_keys.git
      branch: main
jobs:
  - name: terraform
    serial: yes
    plan:
    - get: authorized_keys_repo
      passed: [pipeline]
      trigger: yes
    - task: google-credentials
      file: authorized_keys_repo/.concourse/google-credentials.yml
    - task: terraform
      file: authorized_keys_repo/.concourse/terraform.yml
  - name: pipeline
    serial: yes
    plan:
      - get: authorized_keys_repo
        trigger: yes
      - set_pipeline: self
        file: authorized_keys_repo/.concourse/pipeline.yml